export const FETCH_HOME_DATA = 'FETCH_HOME_DATA';
export const FETCH_HOME_DATA_START = 'FETCH_HOME_DATA_START';
export const FETCH_HOME_DATA_SUCCESS = 'FETCH_HOME_DATA_SUCCESS';
export const FETCH_HOME_DATA_FAIL = 'FETCH_HOME_DATA_FAIL';

export const SORT_DATA = 'SORT_DATA';
export const FILTER_DATA = 'FILTER_DATA';
